vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: '%peinture_image%'
            upload_destination: '%kernel.project_dir%/public%peinture_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
