language: php
php:
  - '7.4'
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS peinture_test;'

script:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
  - php bin/phpunit