language: php
php:
  - '7.4'
services:
  - mysql


install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --if-not-exists --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - ./vendor/bin/simple-phpunit --coverage-text --colors