language:
  - php
  - node_js
php:
  - '7.4'
node_js:
  - 7
services:
  - mysql


install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --if-not-exists --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
  - npm install
  - npm run dev

script:
  - ./vendor/bin/simple-phpunit --coverage-text --colors