language: php
php:
  - '7.4'
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS peinture_test;'

install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - ./vendor/bin/simple-phpunit --coverage-text --colors